spring:
  application: 
    name: factory-demo
  profiles: 
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        '[format_sql]': true
  h2:
   console:
      enabled: true
      path: /h2-console

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      
server:
  port: 8080
       
logging:
  level:
    '[org.hibernate.SQL]': debug
